---
- name: Install Docker on Ubuntu
  hosts: ubuntu
  become: yes

  tasks:

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install required dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker APT repository
      apt_repository:
        repo: "deb https://download.docker.com/linux/ubuntu focal stable"
        state: present

    - name: Install Docker Engine
      apt:
        name: docker-ce
        state: present
        update_cache: yes

    - name: Start Docker service
      systemd:
        name: docker
        state: started

    - name: Enable Docker service on boot
      systemd:
        name: docker
        enabled: yes
